### ISSUE TITLE
Motor synchronisation for constant speed ratio

### ISSUE THREAD

**Issue by ndward** [ev3dev/ev3dev#853]
This message will make the case that **EV3dev badly needs a function that synchronises two motor motions such that the two motors have a constant and correct speed ratio**, thereby also causing the stopping of the motors to be synchronised. This should not be confused with the synchronised _starting_ of motor movements which was the subject of issue 454. Also, motor _regulation_ should not be confused with the _synchronisation_ of two motors. 

Most EV3-compatible languages (EV3-G, RobotC, EV3 Basic, LeJos…) have a function or multiple functions that offer motor synchronisation and it works very well. The motors turn with the requested speed ratio, turn through the correct angles and stop simultaneously. But because EV3dev/EV3 Python does not have such a feature it is, I believe, impossible or very difficult to achieve these results (correct speed ratio, correct angles, simultaneous stop). That's because **individually-controlled EV3 motors usually do not turn with the requested speed**. This was discussed in depth in EV3 Python issue 220 https://github.com/rhempel/ev3dev-lang-python/issues/220 . Summarising that issue, **EV3 motors tend to turn slower than requested for high values of speed_sp** (assuming starting from a standstill, in which case the inertia of the motor stops the motor from having the requested speed at the beginning of this motion). **For low values of speed_sp the EV3 motors tend to turn faster than requested**. This is to do with the difficulty of measuring slow speeds accurately over very small time intervals, though that does not fully explain why there is a systematic tendency for the motors to turn faster than requested. These discrepancies can be very significant. A table in issue 220 shows that for a requested speed_sp value of 50 the actual speed can be more than 20% greater than requested. These discrepancies are due to the properties of the motors themselves and are not EV3dev specific so I would expect other languages to have the same discrepancies but in other languages it would be less of a problem because motor synchronisation allows for the motors to move together with the correct speed ratio through the correct angles.

Rover robots are a classic application of the EV3 and it's vital to be able to make the rover follow a curved path accurately. Other languages can do this thanks to motor synchronisation but I believe EV3dev cannot. It would be banal to configure the move tank block in EV3-G, for example, to make motorB turn with speed 80 for 5 rotations while motorC turns at speed 20, stopping at the same time as motorB . Also, the block would usually be configured to make the program pause until the motors have completed their motions. In EV3 Python the equivalent code might look like this:

```
#!/usr/bin/env python3
from ev3dev.ev3 import *
mB = LargeMotor('outB')
mC = LargeMotor('outC')
mB.run_to_rel_pos(position_sp=1800, speed_sp=800, stop_action='hold')
mC.run_forever(speed_sp=200, stop_action='hold')
mB.wait_while('running')
mC.stop()
```

This code stops the slower motor once the faster motor has finished its movement, which is the behaviour described by Lego for the move tank block in the official documentation. Modifying the code slightly we can see how much each motor rotated:
```
#!/usr/bin/env python3
from ev3dev.ev3 import *
mB = LargeMotor('outB')
mC = LargeMotor('outC')
mB.position=0
mC.position=0
mB.run_to_rel_pos(position_sp=1800, speed_sp=800, stop_action='hold')
mC.run_forever(speed_sp=200, stop_action='hold')
mB.wait_while('running')
mC.stop()
print(mB.position)
print(mC.position)
```

Since motor C is set to turn at a quarter of the speed of motor B and both motors will turn for the same time we are implicitly requesting that motor C turns through a quarter of the angle turned through by motor B, i.e. 450°. In fact my tests show that motor C (starting from rest and with almost no load) turns through about 488°, or about 8% more than requested. This discrepancy is consistent with the observations raised in issue 220, that for small values of speed_sp the motor tends to turn faster than requested. Unlike the EV3 Python script above, the EV3-G move tank block turns the motors through the CORRECT angles because the motors are SYNCHRONISED to maintain the correct speed ratio. Therefore EV3 Python seems to be unable to match the precision of EV3-G in this case due to the impossibility of using synchronised motor movements.

You may be wondering whether a better result could be obtained with this code:
```
#!/usr/bin/env python3
from ev3dev.ev3 import *
mB = LargeMotor('outB')
mC = LargeMotor('outC')
mB.run_to_rel_pos(position_sp=1800, speed_sp=800, stop_action='hold')
mC.run_to_rel_pos(position_sp=450, speed_sp=200, stop_action='hold')
mB.wait_while('running')
mC.wait_while('running')
```

This code will indeed give correct results for the angles turned by each motor but there is still a problem: the slower motor turns faster than requested and the faster motor turns slower than requested (in accordance with issue 220) and therefore the slower motor completes its motion slightly before the faster motor (if you cannot see this effect easily then change the angles in the above code to 18000 and 4500). Therefore the movement happens in two stages: first the two motors are turning but the rover robot is turning less sharply than requested, then motor C stops turning and motor B continues turning for a moment while the rover turns more sharply than requested. This complex and undesired behaviour could be avoided if the motors could be synchronised to maintain a constant and correct speed ratio.

There is another good reason why it would be great to have a synchronised motor function in EV3dev/EV3 Python: it would allow for more concise code. Instead of needing two lines to launch the two motors only one would be needed. And a keyword argument could be included to make the program wait (or not) for the motors to complete their motion before continuing, further shortening the code. Note that the motion described in this message can be achieved in just one line in EV3 Basic :
`Motor.MoveSync("BC", 80, 20, 1800, "True")`
(This means: move motors B and C synchronously with speed B=80, speed C=20, with the faster motor turning through 1800° and the brake applied when the motion completes.)

But we have seen that achieving roughly the same (with less precision!) requires eight lines in EV3 Python. Python has a reputation for being relatively concise so it is disturbing to see that it takes eight times as many lines to achieve the same task compared to EV3 Basic (see my site ev3basic.com). I understand that it is rather difficult to write code for the synchronisation of motors but the developer of EV3 Basic, Reinhard Grafl, was able to write such a function working alone so I am confident that the EV3dev team can manage the same!

**Comment by jabrena** [comment]
Related issue:
https://github.com/ev3dev/ev3dev/issues/454

**Comment by MichaelBuss** [comment]
As a newcomer I can definitely confirm that this would be a great, great feature that would 🚀 my progress. Is it possible to try It out already?

**Comment by dlech** [comment]
As far as I know, no one is working on this.

**Comment by jabrena** [comment]
In the case of the Java development, I will try in the next 2 months.

Next month, I will start testing a Differential Pilot without Motor Synchronisation. 
After testing, I will see the urgency. In LeJOS, the feature was added with EV3 but in RCX & NXT, we didn't use in the past.
http://www.lejos.org/ev3/docs/lejos/hardware/motor/BaseRegulatedMotor.html
https://lejosnews.wordpress.com/2014/10/02/motor-synchronization-problems-part-1/
https://lejosnews.wordpress.com/2014/10/06/motor-synchronization-problems-part-2/

Previous Motor Support:
http://www.lejos.org/nxt/nxj/api/lejos/robotics/RegulatedMotor.html
http://www.lejos.org/rcx/api/josx/platform/rcx/Motor.html

Juan Antonio

**Comment by ndward** [comment]
Interestingly, Reinhard Grafl, the developer of EV3 Basic (see EV3basic.com) has just added three new motor commands, all with synchronisation, to that language. But he points out that 'EV3 basic relies on the Lego firmware to do the hard work' while 'the EV3dev project team … is creating a completely custom firmware for the EV3 brick, so they need to re-invent all the really superb motor control functionality that is part of the original Lego firmware. Especially the synchronized movements are working astonishingly well. So if the EV3dev guys have not included it yet, they probably never will...

**Comment by tcwan** [comment]
Sorry to drag an old issue out of the closet, but I'd like to understand the scope of the problem. Is this something that has to be done in the kernel driver, or is it solvable using user mode library code?

Granted that controlling two motors using the Linux `sysfs` interface won't be very accurate due to the inherent file I/O overheads.

In addition, I found a description of dual motor synchronization algorithms, in Chapter 7.8 pg. 249 of "Mobile Robots: Inspiration to Implementation, 2nd Edition, AK Peters/CRC Press, 1998.  ISBN-13: 978-1568810973 by Joseph L. Jones, Anita M. Flynn, Bruce A. Seiger". Is this typically what is implemented?
(The text of the book is available on the Internet, not sure if it is out of print)

**Comment by dlech** [comment]
It is certainly possible to implement such an algorithm in userspace (using run-direct and duty_cycle_sp), but as you suspect, the sysfs overhead will likely cause problems.

While we would get better results from implementing this in the kernel, I'm learning over time that implementing such things in the kernel is not really the best way to do it. Ideally we would create a character device that allows access to the motors without the overhead of sysfs.

But, since all of the ev3dev libraries are basically just thin wrappers around sysfs, this would break all ev3dev programs ever written.

**Comment by WasabiFan** [comment]
> But, since all of the ev3dev libraries are basically just thin wrappers around sysfs, this would break all ev3dev programs ever written.

What model are you imagining for the interface via a character device? Would it be so different from the existing model that the sysfs-style property interface couldn't internally be implemented in the various libraries to write commands to the stream whenever necessary?

**Comment by tcwan** [comment]
@dlech:

I'm not sure if a character device would be the best way to handle I/O commands, since character devices are byte-stream oriented. The driver would have to parse the input and possibly deal with incomplete command sequence strings.

Normally ioctl() would be the preferred and atomic way of handling I/O commands, but I'm not keen to go down the path of debugging kernel drivers either.

I've been messing with User IO (generic_uio) drivers and using mmap() to perform I/O operations from user space. That might be another way to address the problem by using mmap() and direct I/O register manipulation.

**Comment by jabrena** [comment]
If we create a new method on ev3dev with synchronize features, we could not break anything. Besides, in that level, more members could test the solution.

**Comment by dlech** [comment]
> I'm not sure if a character device would be the best way to handle I/O commands, since character devices are byte-stream oriented

You still need a character device to do ioctl and mmap as you suggested. Also, character devices don't have to be text-based. You can read/write binary data.

What I am envisioning is using an ioctl to set the speed of the motor (or possibly other commands depending on the motor controller) and reading from the char device to get events like a change in position or status flags.

If one waw to use uio to poke hardware registers directly, one would still have to write a userspace daemon that essentially does exactly what the kernel driver does. But one will be at the disadvantage of not having interrupts in userspace and will have to constantly poll the hardware. We almost certainly won't be able to get correct position feedback this way because of missing gpio events.

Really, the ideal solution would be to implement a motor controller in one of the PRUs so that we have hard-realtime control of the motor. Or at a minimum, implement a quadrature encoder in the PRU.

**Comment by dlech** [comment]
> What model are you imagining for the interface via a character device?

The kernel drivers shouldn't try to do things that the motor controller doesn't already know how to do. Trying to do things like ramping and whatnot in the kernel just haven't worked out. So, in the case of the EV3, basically we would just have the equivalent of the run-direct command and the position attribute.

If we implemented a more advanced motor controller in the PRU though, then the kernel interface would look a bit different (more like BrickPi, etc. that have an external motor controller).

**Comment by tcwan** [comment]
@dlech:

UIO does present a rudimentary interrupt handling capability via `uio_pdrv_genirq.ko` module, where you can select() on the uio device file to detect interrupts. It'll not be as efficient compared to a proper kernel driver.

The PRU approach will be specific to the EV3 (and other TI-based SBCs) though, since the other platforms don't have equivalent features?

I am probably crazy to even attempt to do this for Linux, though I'm aware that the PRU exists in the AM1808.

I'll need to study this a bit more, but currently I'd like information on:
1. Build tools for PRU programming. I found a related [article](https://www.embeddedrelated.com/showarticle/603.php) but I haven't read it yet. 
2. Some references on the algorithm to implement (I don't know control theory in detail)

**Comment by dlech** [comment]
> Build tools for PRU programming. I found a related article but I haven't read it yet.

Most of the information about TI PRUs is for newer processors, like AM35xx (BeagleBone). It is very similar, so most of that info is probably applicable. TI has a C compiler for the newer PRUs. I'm not sure if it works for the older AM18xx processor though.

We actually already have a repo for PRU code. https://github.com/ev3dev/ev3dev-pru-firmware. We are using it for extra I2C adapters on BeagleBone. I was able to figure it out by reading the info in the TI wiki. There are some links in the readme for that repo.

> The PRU approach will be specific to the EV3 (and other TI-based SBCs) though, since the other platforms don't have equivalent features?

As I already mentioned, BeagleBone has a very similar PRU, so it should work for that too. Everything else (BrickPi3 and PiStorms) have external microprocessors that do motor control already. The firmware for these is not open-source unfortunately.

> Some references on the algorithm to implement (I don't know control theory in detail)

paging @laurensvalk

**Comment by jabrena** [comment]
Hi @dlech, if you need hand for testing or a bit od development, tell me.

**Comment by tcwan** [comment]
@dlech:

1. Based on [motor drive ports](http://www.ev3dev.org/docs/kernel-hackers-notebook/ev3-pwm/), I guess we should use outA and outB as the synchronized motor ports?

> Ideally the control algorithm should not be constrained by 2 motors only, but let's worry about the basic functionality first.

2. How do you get the tachometer readings? Which AM1808 peripheral is used?
> Will this be different for NXT and servo motors?

3. I presume that only PRU1 is available since [PRU0](http://www.ev3dev.org/docs/kernel-hackers-notebook/ev3-uart/) is being used for UART3 and 4. Would that be similar for the Beaglebone?

4. The part I'm most confused by currently is how to interface with the motor driver and obtain tachometer readings. 
   - I presume that we would need a new Linux kernel driver to interface with the PRU, and communicate with the PRU via some form of memory mapped buffer.
   - the PRU only implements the control algorithm
   - commands to update the motor settings will be done by the kernel driver (this may have latency / jitter issues)
   - tachometer readings will be passed by the kernel driver to the PRU

>Edited:
> From the [description](http://processors.wiki.ti.com/images/1/18/PRUSS_Training_Slides.pdf) of the PRU, the RISC engine would have access to I/O pins directly controlled by itself, as well as the low level hardware module (e.g., EPWM0/1). 
>However, I'm no sure if it is a good idea to mess with the PWM directly without going through the normal kernel driver path. In addition, I'd rather not worry about overdriving the motors if possible.

5. I still have not managed to determine if the [PRU C compiler](http://www.ti.com/tool/PRU-SWPKG) is able to support the AM1808 PRU,  but worst case we can extract the C compiler ASM output and sanitize it for the AM1808 if necessary.

**Comment by dlech** [comment]
> Based on motor drive ports, I guess we should use outA and outB as the synchronized motor ports?

Actually, I would use B and C since that is what official LEGO models use for drive/steering motors.

> How do you get the tachometer readings? Which AM1808 peripheral is used?

They are attached to GPIOs, so we have to watch for interrupts and use a state machine to figure out which direction we are turning. Wikipedia has some decent introductory info if you are not familiar with this: https://en.wikipedia.org/wiki/Rotary_encoder#Incremental_rotary_encoder


> I presume that only PRU1 is available since PRU0 is being used for UART3 and 4. Would that be similar for the Beaglebone?

Yes. (on BeagleBone [PRU0 is free](https://github.com/ev3dev/ev3dev-pru-firmware/blob/master/evb-pru0/main.c))

> The part I'm most confused by currently is how to interface with the motor driver and obtain tachometer readings.

Actually, I was hoping to do it the other way around. The PRU should monitor the GPIOs for the quadrature encoder and determine the motor position based on this. Then the kernel driver can just read the motor position from the PRU.

> I presume that we would need a new Linux kernel driver to interface with the PRU, and communicate with the PRU via some form of memory mapped buffer.

It might be worthwhile to make a new kernel driver for testing, but we should be able to use the existing driver and just replace certain parts of it. There are shared memory addresses between the PRU and the CPU (i.e. 0x01C30000 to 0x01C301FF - comes from http://processors.wiki.ti.com/index.php/PRUSS_Memory_Map - will be different for BeagleBone)

> the PRU only implements the control algorithm

And also the quadrature encoder (as mentioned above). In fact, I think it would be a good idea to just implement the quadrature encoder to begin with just to get the hang of how things work and then add a control algorithm later.

> commands to update the motor settings will be done by the kernel driver (this may have latency / jitter issues)

Correct. However, if we can get the quadrature encoder in the PRU, then using the RT kernel patchset might be a possibility. It will reduce the jitter, but at the expense of making everything else run even slower than it already does on the EV3.


> I still have not managed to determine if the PRU C compiler is able to support the AM1808 PRU, but worst case we can extract the C compiler ASM output and sanitize it for the AM1808 if necessary.

:+1:

**Comment by dlech** [comment]
If you are really serious about working on this, I can probably come up with a kernel driver fairly quickly for testing that just loads the PRU firmware and maps the shared memory.

**Comment by tcwan** [comment]
> If you are really serious about working on this, I can probably come up with a kernel driver fairly quickly for testing that just loads the PRU firmware and maps the shared memory.

Well, I'm curious enough to give it a stab.
Just monitoring the quadrature encoders sounds doable for now.

However, I'm not sure how to arbitrate access to the quadrature encoder GPIOs between this and the tacho motor driver. Would it be ok to just poll them, then I don't have to worry about interrupt handlers which are probably being used by the regular tacho motor driver currently?

Should I do this using the [ev3dev-pru-firmware](https://github.com/ev3dev/ev3dev-pru-firmware) repo?

Finally what version of CSS should I use? The latest release is version 8.

**Comment by dlech** [comment]
> Well, I'm curious enough to give it a stab.
> Just monitoring the quadrature encoders sounds doable for now.

Great. If you give me a few days, I'll try to clean up the PRU UART code and create a new driver template for loading your firmware in the other PRU.

> However, I'm not sure how to arbitrate access to the quadrature encoder GPIOs between this and the tacho motor driver. Would it be ok to just poll them, then I don't have to worry about interrupt handlers which are probably being used by the regular tacho motor driver currently?

The PRUs have their own "interrupt controllers". I put this in quotation marks because "interrupts" don't actually trigger an interrupt handler like you may be accustomed to. So, you basically have to poll the GPIOs even if you do use "interrupts". And, you don't have to worry about affecting the ARM interrupt controller.

Given that and the fact that we are using these GPIOs as inputs, you don't have to worry about conflicting with the current motor driver.

> Should I do this using the ev3dev-pru-firmware repo?

That would be the best place to submit PRU code.

> Finally what version of CSS should I use? The latest release is version 8.

Latest version is probably the best. I haven't touched it in a while.

**Comment by tcwan** [comment]
Ok. I found a [reference project](http://www.ti.com/tool/TIDEP0073)  which may be a good starting point.

>There's a more advanced [example](http://processors.wiki.ti.com/index.php/PRU_ICSS_Industrial_Drives#) but I can't seem to find the source files. They may be part of the Processor SDK installation.

>Edit: As usual, silicon vendors have ridiculously convoluted IDE and SDK naming as well as releases. From what I can gather, I need the Processor SDK to get the PRU compilers, and the [Processor SDK only works with CCS version 7.x](http://software-dl.ti.com/processor-sdk-rtos/esd/docs/latest/rtos/Overview.html#processor-sdk-rtos-getting-started-guide) currently.

>They have Processor support for [OMAP-L138](http://www.ti.com/tool/processor-sdk-omapl138), which is basically the AM1808 + DSP in a single package. I will look into using that package for now.

Edit 2: Sitara device support is only available in Linux / Ubuntu and Windows version of CCS. I think I don't actually need the Processor support packages which are for their own Linux distro or RTOS.

The PRU compiler is installed via CCS App Center (I think you can probably access everything through CCS App Center or the Resource Explorer). I'm going to use CCS version 8 since it is the currently maintained version.

The code for the PRU Industrial Drive package is not linked from the information page. Instead, it is [here](http://www.ti.com/tool/PRU-ICSS-INDUSTRIAL-SW).

**Comment by tcwan** [comment]
I don't see any Issues tab for the ev3dev-pru-firmware project, so I'm dumping the info here for future reference:

### LEGO Motor Ports Info
- Refence: Lego EV3 Hardware Developer Kit, Appendix 1.
- Output Ports Pin 5 and 6 are used for Tacho inputs
- Pin 5 acts as interrupt source (INTx0), x=A,B,C,D
- Pin 6 provide direction info (DIRx), x=A,B,C,D
- Connections:
   - INTA0: EMA_A11/GP5_11
   - INTB0: EMA_A8/GP5_8
   - INTC0: EMA_A13/GP5_13
   - INTD0: UHPI_HHWIL/UPP_CHA_ENABLE/GP6_9
   - DIRA:  ARX12/FSR1/GP0_4
   - DIRB:  EMA_BA1/GP2_9
   - DIRC:  nEMA_CS3/GP3_14
   - DIRD:  EMA_BA0/GP2_8

**Comment by tcwan** [comment]
![quadrature-encoder-states](https://user-images.githubusercontent.com/105933/41652079-be29e4d4-74b4-11e8-95e4-a537f29e59be.png)

My first stab at creating a State machine to capture the behavior of the quadrature encoder. This uses 9 states, for clarity. It can be simplified down to 5 (or even 4 states) at the expense of more complex transitions.

Edit 2 : Updated with the reverse transition from CCW to CW states.

**Comment by laurensvalk** [comment]
Thanks for working on this @tcwan 

To make this also valuable for speed measurements, it would be helpful to keep a FIFO array of hardware timer values corresponding to equidistant transitions.

Essentially adding a time stamp to each count +/- degree transition. Integer clock counts are sufficient. Is memory a concern here? I think keeping a FIFO array of about 100 transition times will be more than enough.

The actual speed computation is something interesting to think about. This does not have to be done by the PRUs. Having accurate transition time data is key in any case though, and the PRUs could do this nicely.

The same goes for controllers. When accurate timing is available from the PRU in shared memory, the kernel or the user program can compute control signals (PID, etc). And this would need to be done much less frequently compared to handling pin interrupts. 

-------

The current ev3dev speed computation does not work very well, which limits the usability of the run-to- pos/abs/time/forever commands. 

To see this, run any motor at a constant physical speed (in run-direct mode at e.g. 60% duty cycle) with no load on the motor. Display the speed readings as you go along.

Not only do they vary quite a bit (even though the physical motor speed is constant), they are also quite far off from the actual speed, where the actual speed is obtained by running for e.g. 50 seconds and displaying (end_pos - start_pos)/50.

**Comment by tcwan** [comment]
![quadrature-encoder-states-simplified](https://user-images.githubusercontent.com/105933/41654467-23da267a-74bc-11e8-94ee-dfe31a206b50.png)

After looking at the original state transitions, I think it is easier just to simplify it to a 5-state version.

@laurensvalk, thanks for the info. I'll have to explore this issue more to understand how to best implement it.

**Comment by dlech** [comment]
> To make this also valuable for speed measurements, it would be helpful to keep a FIFO array of hardware timer values corresponding to equidistant transitions.

We can use the top half of TIMER64P0 (register TIM34) for this timestamp. It is configured as a free running 32-bit counter already by the OS. And it always runs at 24MHz.

We can use the iio subsystem to expose the FIFO to userspace... but one thing at a time.

> Is memory a concern here?

There is an 8K "ARM Local RAM" and a 128K "On Chip RAM" at our disposal (a small portion of each is already used). Thinking out loud: 4K would get us 500 events (4 bytes for timestamp + 4 bytes for position). If we double the precision (see #148), then assuming a max speed of 2000 deg/sec (actual max speed of medium motor will full batteries is something like 1600 deg/sec, so there is a pretty good margin for safety figured in here), we would get a max of 4000 events per second, which means we would have to drain the FIFO from userspace every 125ms in order to not miss any events.

> This does not have to be done by the PRUs.

I'm very much in favor of doing a little as possible in the PRU to make it more flexible. So, if we can just get away with doing timestamps and not calculating speed, I'm all for it.

**Comment by dlech** [comment]
@tcwan, I've managed to get a blinking LED working with the PRU on the EV3.

You will need to build your own kernel from https://github.com/ev3dev/ev3-kernel. You will need swap the "disabled" and "okay" shown [here](https://github.com/ev3dev/ev3-kernel/commit/4a6d4c21ff598e9cb225331d009ba969aa25d119#diff-f35616aa4e18d463c186c51c2308b79f) to enable the new remoteproc driver. You may also find it helpful to enable the `DEBUG_FS` compile option.

Then, build the ev3-pru-test project from https://github.com/ev3dev/ev3dev-pru-firmware. Copy the `ev3-pru-test.out` file to `/lib/firmware/` on the EV3. After a reboot, you should see the left green LED blink constantly.

**Comment by laurensvalk** [comment]
Thinking about timers some more, there is an easier way to get speed measurements. It's almost equally accurate, but the implementation is much closer to what we have now, making the process easier on the kernel side, compared to the approach I mentioned above.

I suppose the timer can also be used to trigger interrupts on the PRU? If so, we can fire one separate interrupt routine every X clock ticks to store the present encoder value of each motor in a FIFO array. Since the interrupt frequency is known, there is no need to store timer values. Also, the time stamps are the same for each motor.

Speed is then computed in the kernel by taking the most recent position, minus the position Y trigger instances ago, divided by the time between them (which is always constant). I use this approach for the Segway. That bit of code is [here](https://github.com/laurensvalk/segway/blob/eab678399ada5b563c497a0a4e190f082b796184/ev3/ev3dev/pythonic/filters.py#L57). But with samples stored by the PRU it would be much more accurate.

The parameter Y (window size) could be a user configurable parameter. A longer window gives you smoother speed values with a slight delay in them, and vice versa.

**Comment by dlech** [comment]
> I suppose the timer can also be used to trigger interrupts on the PRU?

The PRU can't do interrupts in the conventional sense. (There is an "interrupt controller", but is just sets and clears flags and can't call an ISR). So, the only way to do something every X clock ticks is busy-waiting until we see the "interrupt".

> The parameter Y (window size) could be a user configurable parameter.

Not a bad idea, but making stuff in the kernel and PRU "user configurable" has proved to be difficult to implement, so I would like to avoid this if there are other reasonable options.

**Comment by laurensvalk** [comment]
>  Thinking out loud: 4K would get us (...)

For speed computations, I think storing the last 2 bytes of the encoder position is more than enough because we only need the position differences. Even if we considered measurement windows of a second, you can hit up to 65536/360*60=11K RPM before running out of bits.

The position counter would still be stored in 4 bytes.

**Comment by laurensvalk** [comment]
> The PRU can't do interrupts in the conventional sense.

Ah, in that case the first approach may still be necessary. I'll think about that. 

> > The parameter Y (window size) could be a user configurable parameter.

> Not a bad idea, but making stuff in the kernel and PRU "user configurable" has proved to be difficult to implement, so I would like to avoid this if there are other reasonable options.

In principle, Y would only be a parameter in the final computation (which does not take place on the PRU). It would not be much different than changing the currently used Kp/i/d parameters.

However, a sensible fixed value should suffice indeed.

**Comment by laurensvalk** [comment]
> >The PRU can't do interrupts in the conventional sense.

> Ah, in that case the first approach may still be necessary. I'll think about that.

On second thought, if some sort of state machine is required to busy-wait for encoder pin pulse flags anyway, it's perhaps not really a stretch to add one short interrupt driven routine that stores the motor positions.

**Comment by tcwan** [comment]
@dlech: 
>You will need to build your own kernel from https://github.com/ev3dev/ev3-kernel. You will need swap the "disabled" and "okay" shown here to enable the new remoteproc driver. You may also find it helpful to enable the DEBUG_FS compile option.

Does this replace the in3 and in4 sensor driver? If so, then I'll be writing code to run on PRU0, am I correct?

**Comment by dlech** [comment]
The existing PRU UART driver basically hogs all of the PRU memory addresses, so you have to disable it in order to use the new PRU remoteproc driver. This is orthogonal to the input port drivers. UART sensors won't work on input ports 3 and 4, but that is the only side effect.

The current PRU remoteproc driver only loads firmware into PRU0, so use that one for now.

**Comment by tcwan** [comment]
@dlech:

I can't seem to find any information on how to build the ev3-kernel source.
I presume that I should be using the ev3dev-stretch branch.

Do I build it using the stretch docker image?

**Comment by dlech** [comment]
https://github.com/ev3dev/ev3dev-buildscripts

**Comment by tcwan** [comment]
@dlech:

>There is an 8K "ARM Local RAM" and a 128K "On Chip RAM" at our disposal (a small portion of each is already used)

Actually the `12K` (sic) memory mapped RAM (shared with the ARM CPU) is only available on the [AM335x CPU](http://processors.wiki.ti.com/index.php/PRU-ICSS_Feature_Comparison), so EV3 would not be able to take advantage of it. In addition, the EV3 only has 512 bytes of dedicated PRU "Local RAM"

It would still be nice to be able to do accurate motor control using the Beaglebone though.

**Comment by dlech** [comment]
The PRU has access to most on-chip peripherals, including to two RAMs I mentioned. They are both different from the 512B PRU local RAM.

**Comment by tcwan** [comment]
@dlech:
>The PRU has access to most on-chip peripherals, including to two RAMs I mentioned. They are both different from the 512B PRU local RAM.

From the global memory map, there are 3 types of memory associated with the PRUs:
1. Local Data RAM (512 bytes for EV3, 8K for Beaglebone)
2. Shared main DRAM (0 for EV3, 12K for Beaglebone)
3. Local Instruction RAM (4K for EV3, 8K for Beaglebone)

1 and 2 (where available) should be usable for data storage. I'm not sure if 3 can be used from within the PRU to store data since it looks like a Harvard architecture device where the Instruction Address space and Data Address space are separate.

**Comment by dlech** [comment]
Have a look at the AM1808 datasheet, there are additional SoC RAMs not listed in the PRU docs.

**Comment by dlech** [comment]
FWIW, the existing PRU UART driver uses the first 8K of the 128K RAM.

**Comment by tcwan** [comment]
@dlech:

Ok. I see the on-SoC DRAM listed. I'm not sure how to access it yet, based on the PRU Memory Map info in the PRUSS_Training_Slides.pdf.

The AM1808 Technical Reference (spruh82a) doesn't even talk about the PRU, it links to the [TI Wiki](http://processors.wiki.ti.com/index.php/Programmable_Realtime_Unit).

**Comment by dlech** [comment]
The DDR RAM is yet another RAM, don't use it. It is owned by the Linux kernel. You can do something like this:

```c

typedef struct {
    uint32_t timestamp;
    uint32_t position;
} event;

#define ON_CHIP_RAM ((volatile event *)(0x80000000))

...

    ON_CHIP_RAM[0].timestamp = 123456;
    ON_CHIP_RAM[0].position = 99;
```

See Table 3-2 in the "data sheet" (not the technical reference).

**Comment by tcwan** [comment]
@dlech:
From the ev3dev-buildscripts README.md:
```
~/work/ev3dev-buildscripts $ cd ./build-area/linux-ev3dev-ev3-dist
~/work/ev3dev-buildscripts/build-area/linux-ev3dev-ev3-dist $ cp uImage <path-to-boot-partition>/uImage
~/work/ev3dev-buildscripts/build-area/linux-ev3dev-ev3-dist $ sudo cp -r lib/ <path-to-file-system-partition>

```
Then later:
```
# replace `/mnt/ev3dev-root` with your actual mount point
export EV3DEV_INSTALL_KERNEL=/mnt/ev3dev-root/boot/flash
export EV3DEV_INSTALL_MODULES=/mnt/ev3dev-root
```

/dev/sde1 contains the u-boot.bin first stage boot loader, which isn't the Linux root file system.

```
$ sudo mount /dev/sde2 /mnt/sdcard

$ ls /mnt/sdcard/boot
boot.scr                         dtbs
boot.scr.bak                     flash
config-4.14.49-ev3dev-2.0.2-ev3  initrd.img-4.14.49-ev3dev-2.0.2-ev3
dtb                              System.map-4.14.49-ev3dev-2.0.2-ev3
dtb-4.14.49-ev3dev-2.0.2-ev3     vmlinuz-4.14.49-ev3dev-2.0.2-ev3
```
Where should the uImage file go? I don't find any files in the /boot/flash directory.
By right the kernel image is vmlinuz-\*, but I probably need to rebuild initrd.img* as well, which isn't part of the instructions.

I think I should also replace the *dtb with the updated versions.

[Edited]

**Comment by dlech** [comment]
The readme is a bit out of date with recent changes to the bootloader in the stretch images. I think the easiest way to get everything in the right place is to create a debian package (the readme also explains how to do this).

BTW, pining me on IRC or Gitter is probably the best for these types of questions.

**Comment by tcwan** [comment]
@dlech:

I've checked in a dummy [PRU driver](https://github.com/tcwan/ev3dev-pru-firmware/tree/ev3-tacho-encoder) in my repository, under the `ev3-tacho-encoder` branch. 
I've just adopted the existing software license from the TI PRU source files, not sure if you have any specific preference.

Basically the PRU driver alternatively blink the left and right LEDs. I'll be using the LEDs to debug the tacho count logic later.

We need to define the data structure for storing the encoder values. Are we storing timestamp, encoder count, or both? Do we need to store the whole 32-bits or only the lower 16-bits (we can store the starting value as 32-bit). I presume that we should have some kind of ring buffer logic for generating and consuming the values. Should we cater for multiple motors (more than 2) in the data structure if possible?

In addition, I'm thinking of using a [lock-free ringbuffer](https://github.com/rmind/ringbuf) but I don't have any specific implementation in mind. The URL was just the first hit Google returned.

**Comment by laurensvalk** [comment]
Of course you are welcome to choose your own scheme but I thought I'd sum up my proposal above for brevity:

------------

I would store the current ``count`` variable in your diagram as a 32-bit variable.

And after every ``n_time_cycles`` (a constant integer) clock cycles, store the last 16 bits of the current ``count`` value, in an array ``count_history`` of length ``n_window``. (If memory is no issue, you might as well store 32-bit arrays for consistency.)

No time stamps would be needed for this approach.

To get a FIFO-like behavior without shifting array data, you could keep a continuously incrementing index value (modulo its length) corresponding to the oldest value. Each time the clock is triggered, the new 16-bit value overwrites the oldest one. 

The speed integer value (with units of ``count_diff`` per ``n_window*n_time_cycles/pru_freq`` seconds) is simply the newest position minus the oldest one before it gets purged. The kernel can later scale it to something like degrees per second with a constant scaling factor.

The kernel would need access to the 32 bit position counter ~~, the array of 16-bit values, and the running index value.~~ and the unscaled speed value.

Let me know if pseudocode of this would be helpful.

------

For four motors, this is  four 32-bit ``count`` positions, and four 16-bit ``count_history`` arrays, each of a constant length ``n_window``. 

The counters get upgraded according to the state machine (one state machine for each motor)

All 4 arrays get updated once every  ``n_time_cycles`` cycles (one update routine for all four motors). So one would have to keep ~~and share~~ only one index value.

~~Above I'm assuming that the kernel can read the shared memory without the PRU updating it in the mean time.~~

**Comment by dlech** [comment]
> And after every n_time_cycles (a constant integer) clock cycles

How often do we need to do this to be useful? 1kHZ, 10kHz, 100kHz?

**Comment by tcwan** [comment]
@laurensvalk:

Thanks for the input. I think I understand what you're describing in terms of the data capture and storage.

I'd just like to ask whether 4 motors would be the maximum in terms of tachometer reading support. We would still only be able to display the state for two motors at any given time on the Left and Right LEDs, but there is no problem keeping track of multiple motor tacho counts.

**Comment by dlech** [comment]
> I've just adopted the existing software license from the TI PRU source files, not sure if you have any specific preference.

That's what I have been doing too, rather than dealing with two different licenses.

> Should we cater for multiple motors (more than 2) in the data structure if possible?

Yes, we want the same data from all 4 motors.

**Comment by tcwan** [comment]
A question regarding ring buffer management:

Is it better to keep the latest X entries (FIFO), or discard new entries once the buffer is full?

**Comment by dlech** [comment]
discard the old entries so that the ring buffer always has the most up to date information.

**Comment by laurensvalk** [comment]
> How often do we need to do this to be useful? 1kHZ, 10kHz, 100kHz?

1kHz is more than enough. Even 100 Hz will probably do. I think the main gain will be consistency. 

At 24MHz PRU clock and storing samples at, say, 1.2kHz, this means updating the arrays once every time the timer exceeds a multiple of 20 000 timer ticks. That seems feasible, right?

As a starting point, I think a window size of 10-50 ms would be a useful target. Say we pick a window size of 25 ms and we can manage 1.2kHz of sample rate. Then the buffer length ``n_window`` is 30.

**Comment by laurensvalk** [comment]
In this post, I'm adjusting the values above to get simpler integer arithmetic while avoiding complications with round-off and overflow errors. This way you can get the ring buffer index directly from the timer. Here's some pseudo code.

PRU Constants and array initialization
```
#define n_time_cycles = 2^14 = 16384
#define n_window = 2^5 = 32
// Initially entire array is equal to current count value
int count_history_A[n_window] = {count_A, ....., count_A};
int count_history_B[n_window] = {count_B, ....., count_B};
int count_history_C[n_window] = {count_C, ....., count_C};
int count_history_D[n_window] = {count_D, ....., count_D};

```
Make the PRU call the following routine each time after ``n_time_cycles`` clock ticks. So each time the 15th least significant bit of the timer toggles. (There's no particular rush as long as it surely gets called before it toggles again; handling intermediate motor pulse interrupts should pose no threat.) 
```
//Read timer
timer = read_clock_32_bit()

// Get index for the ring buffer
// The integer floor division within the brackets can be done as bit shift instead.
// The % indicates modulo.
time_index = (timer / n_time_cycles) % n_window 

//Read oldest value before we overwrite it
oldest_count_A = count_history_A[time_index]
oldest_count_B = count_history_B[time_index]
oldest_count_C = count_history_C[time_index]
oldest_count_D = count_history_D[time_index]

// The current motor position
newest_count_A = count_A
newest_count_B = count_B
newest_count_C = count_C
newest_count_D = count_D

//Store the current count value
count_history_A[time_index] = newest_count_A
count_history_B[time_index] = newest_count_B
count_history_C[time_index] = newest_count_C
count_history_D[time_index] = newest_count_D

//integer speed computation
unscaled_speed_A = newest_count_A - oldest_count_A
unscaled_speed_B = newest_count_B - oldest_count_B
unscaled_speed_C = newest_count_C - oldest_count_C
unscaled_speed_D = newest_count_D - oldest_count_D
```

If the kernel has read access to the unscaled_speed variables, it can convert those numbers to physical speed like degrees per second, with a single multiplication. No need to access the motor history buffers.

Speed conversion done by the kernel:
```
//Constants
ticks_per_degree = 1 // Or 2 if precision is doubled
time_window = n_time_cycles*n_window/24000000

// Speed computation
speed_A_degrees_per_second = unscaled_speed_A / (ticks_per_degree * time_window)
speed_B_degrees_per_second = unscaled_speed_B / (ticks_per_degree * time_window)
speed_C_degrees_per_second = unscaled_speed_C / (ticks_per_degree * time_window)
speed_D_degrees_per_second = unscaled_speed_D / (ticks_per_degree * time_window)
```

**Comment by tcwan** [comment]
Hi,
I've created the tacho encoder module, but I'm hitting the max code size limit (4K) on the AM1808. Will need to go through the code and refactor something.

```
$ size *obj
   text	   data	    bss	    dec	    hex	filename
   1228	      0	     46	   1274	    4fa	leddebug.obj
    380	     20	    136	    536	    218	main.obj
   2832	      8	     30	   2870	    b36	tacho-encoder.obj
```

Note: The `EV3_TACHO_TESTCASE2` works because it doesn't link in the tacho-encoder routines.

**Comment by dlech** [comment]
Yeah, this is going to have to be absolute minimum not frills, almost like you are writing assembly code instead of C code. Also, make sure you are building the release target with compiler optimizations enabled. I was hoping to cram more into the PRU, so if just the tacho code is filling up the whole instruction memory, that is not good.

**Comment by tcwan** [comment]
After some pointer optimizations, and with '-O2' and optimized for size (-opt_for_speed=0), I'm getting:
```
$ size Debug/*obj
   text	   data	    bss	    dec	    hex	filename
    796	      0	     42	    838	    346	Debug/leddebug.obj
    380	     20	    136	    536	    218	Debug/main.obj
   2480	      8	     30	   2518	    9d6	Debug/tacho-encoder.obj
```
~~However, I still can't link the executable file.~~
Edit: it was a silly bug in the function defintion naming. It can link properly now.

In any case, after I took out the motor->port mapping and per-motor enable-disable logic in the `default-port-mapping` branch, I'm getting:
```
$ size Debug/*obj
   text	   data	    bss	    dec	    hex	filename
    548	      0	     42	    590	    24e	Debug/leddebug.obj
    276	     20	    136	    432	    1b0	Debug/main.obj
   1212	      0	     25	   1237	    4d5	Debug/tacho-encoder.obj
```

Edit: I presume that the default linker settings will not include functions that are not called.

**Comment by tcwan** [comment]
I've merged the `default-port-mapping` branch back into the `ev3-tacho-encoder` branch.

The code can be tested using a motor attached to outA (first motor port).
It should be blink green in one direction and red in the other direction, else orange if it thinks that the direction is unknown.

When I tested it with a EV3 medium servo motor connected to outA, at first it was working ok, then suddenly the motor was disconnected from the port, and after I removed the cable and reinserted it, I'm getting orange more often than not.

Testing with a EV3 large servo motor was pretty dismal as well. It was mostly orange.

Are the GPIO inputs (quadrature encoder inputs) noisy? Maybe I shouldn't transition to the unknown state every time I don't see an expected transition?

**Comment by dlech** [comment]
I didn't think they were too noisy. They have schmitt triggers on them.

**Comment by tcwan** [comment]
@dlech:

Can you give it a try and see what you observe? I'm not sure where to focus my attention for debugging this. In addition, how would I be able to access the 128K On-chip-RAM buffer to inspect the values from the shell? I've built DEBUG_FS and I can mount the debugfs in my build.

**Comment by tcwan** [comment]
Thanks to @dlech 's help, I've fixed a silly enum definition bug and tagged the `ev3-tacho-encoder` branch with the `EV3_TACHO_v0_PROTOTYPE` tag which works by blinking the green and red LEDs correctly.

Edit: Released `EV3_TACHO_v0.1_PROTOTYPE` which tracks Left (outB) and Right (outC) motors. Forward rotation is Green, Reverse rotation is Red. Unknown state (shoudn't happen under normal circumstances when rotating) is Orange.

**Comment by dlech** [comment]
I'm still getting some orange with a medium motor after this fix.

**Comment by tcwan** [comment]
@dlech:

But is the medium motor showing the correct green (forward)/red (reverse) for the rotation direction in general?

**Comment by dlech** [comment]
no, it is orange unless the motor has stopped moving

**Comment by dlech** [comment]
Update: I realized that I had a mainline kernel loaded instead of an ev3dev kernel. After switching back to the ev3dev kernel, the medium motor is working as expected. I'm going to guess that there was a pinmux/pinconf issue since the mainline kernel doesn't touch the output ports. So, no problem after all.

**Comment by laurensvalk** [comment]
Not sure if this is technically feasible, but it may be worthwhile to leave at least one motor on the old driver for now while debugging, as a sanity check. 

Then mechanically link those motors, and watch whether the positions values are the same. 

Or, it it's easier, use a second EV3 for the verification process.

**Comment by dlech** [comment]
I was going to post this, the @laurensvalk recommended it as well, so it must be good. :smile: 

This is a quadrature encoder that is built into the BeagleBone, so it would be good to model ours after it. At least the parts we are interested in (position and speed - we don't have things like an index pulse obviously).

http://www.ti.com/lit/ug/sprug05a/sprug05a.pdf

**Comment by tcwan** [comment]
@dlech:

I read the TI Reference Guide. I think the PRU side is mostly done except for the driver<->PRU control channel. The behavior of the encoder may be slightly different as I introduce an intermediate state when I don't see the expected transition, so the count may be off by a quarter revolution.

Otherwise, the actual motor control part should be in the driver itself, based on the previous discussions. Not sure if you plan on working on that though.

**Comment by tcwan** [comment]
@laurensvalk:

Ideally the motors can be assigned and unassigned from the normal motor driver to the synchronized motor driver. They should initially start off as unsynchronized motors.

I don't know what is the best mechanism to support this though.

**Comment by dlech** [comment]
@tcwan:

Yesterday, I created a new driver and PRU firmware that takes care of the PRU to kernel communication. If you can patch your encoder logic into [ev3-pru0](https://github.com/ev3dev/ev3dev-pru-firmware/blob/master/ev3-pru0/main.c) we will see what happens.

The buffer is handled mostly in the kernel, so we don't need any ring buffer stuff in the PRU.

**Comment by tcwan** [comment]
Ok. I'll try to see how to integrate them. Would the firmware loading process be identical to the current setup?

**Comment by dlech** [comment]
yes, the loading process is still the same for now

**Comment by dlech** [comment]
All:

Here is a package for testing. Detailed instructions are in the zip file.

[ev3-pru-tacho.zip](https://github.com/ev3dev/ev3dev/files/2147030/ev3-pru-tacho.zip)

Basically, the status is that we can now read tacho counts for all 4 motors plus a timestamp (in nanoseconds) all at once. The values are updated every 5ms. 

I would like to see some people play around with this and do some data analysis so that we can figure out the best way to calculate speed and whatnot.

One thing I've noticed is that the first couple of sets of values that you read are stale. The number of sets corresponds to the number returned by `/sys/bus/iio/devices/iio\:device1/buffer/length`, so you can use that to skip those values if needed.

**Comment by tcwan** [comment]
>One thing I've noticed is that the first couple of sets of values that you read are stale. The number of sets corresponds to the number returned by /sys/bus/iio/devices/iio\:device1/buffer/length, so you can use that to skip those values if needed.

I wonder if this is due to firmware loading to the PRU taking place after the the iio channel was setup? There doesn't seem to be any buffer flush function call available for the iio subsystem.

**Comment by dlech** [comment]
> I wonder if this is due to firmware loading to the PRU taking place after the the iio channel was setup?

No, if you close and re-open the iio device, then you get stale values again. This is a [known limitation of reading this character device directly](https://wiki.analog.com/resources/tools-software/linux-software/libiio_internals#reading_and_writing_the_old_way).

**Comment by tcwan** [comment]
@dlech:
I'm wondering if there is some bug in the `pru_virtio_ring.h` `vring_init()` function:
```
#define vring_used_event(vr) ((vr)->avail->ring[(vr)->num])
#define vring_avail_event(vr) (*(__u16 *)&(vr)->used->ring[(vr)->num])

static inline void vring_init(struct vring *vr, uint32_t num, void *p,
                              uint64_t align)
{
	vr->num = num;
	vr->desc = p;
	vr->avail = (void *)((char *)p + num*sizeof(struct vring_desc));
	vr->used = (void *)(uintptr_t)(((uint64_t)&vr->avail->ring[num]
	                                + sizeof(uint16_t) + align-1) & ~(align - 1));
}
```
~~Specifically `vr->used` is initialized to the `avail->ring[num]` pointer, so it starts off with dummy events in the queue.~~
Else, `vring_used_event()` is referencing `vr->num` which is initialized to a non-zero value at the start.
However, the code is quite convoluted so I don't know for sure.

Edit2: changed `vring_avail_event()` to `vring_used_event()` since sending messages to user space places items into the `used` vring.

**Comment by dlech** [comment]
can you open a new issue for the vring bug?

**Comment by dlech** [comment]
[ev3-pru-tacho-v2.zip](https://github.com/ev3dev/ev3dev/files/2151388/ev3-pru-tacho-v2.zip)

Here is a v2 for testing. It adds some data points so that we can compare the two methods of measuring speed described in the document mentioned [above](https://github.com/ev3dev/ev3dev/issues/853#issuecomment-400857689).

The new values are measuring the duration of 8 counts.

So basically, now we can do both equations (1) and (2) on page 10.

**Comment by tcwan** [comment]
@dlech:

~~I think you need longer pause in restart.sh after `modprobe -r ev3-pru`.~~
Edit (`modprobe` wasn't the cause): I think you need longer pause in restart.sh after `echo start`. `sleep 2` seems to work fine.

```
sudo bin/restart.sh 
[sudo] password for robot: 
bin/restart.sh: line 3: echo: write error: Invalid argument
bin/restart.sh: line 15: /sys/bus/iio/devices/iio:device1/scan_elements/in_count0_en: No such file or directory
[...]
```

The second time around it will succeed.

**Comment by tcwan** [comment]
I've given version 2 a try using test.py, but I think the delta-T (equation 2) presentation is a bit confusing. I'm only adjusting the servo position by hand, so it is not a constant rotation speed.

Some observations:
1. The read speed using python is slow, so the timestamps are 5ns for 2 entries, after which it will pause for 10-20 ns before being able to send a new update.
Edit: Ignore the first 2 entries since they're stale (timestamp `293.xxx`)
```
0 -271 -179 0 0.0 3.0506545 0.06891391666666667 0.0 293.680000416
0 -271 -179 0 0.0 3.0506545 0.06891391666666667 0.0 293.685000375
0 -271 -179 0 0.0 3.0506545 0.06891391666666667 0.0 521.650001583
0 -271 -179 0 0.0 3.0506545 0.06891391666666667 0.0 521.655000291
0 -271 -179 0 0.0 3.0506545 0.06891391666666667 0.0 521.675000708
0 -271 -179 0 0.0 3.0506545 0.06891391666666667 0.0 521.6800005
0 -271 -179 0 0.0 3.0506545 0.06891391666666667 0.0 521.695002375
0 -271 -179 0 0.0 3.0506545 0.06891391666666667 0.0 521.700000166
0 -271 -179 0 0.0 3.0506545 0.06891391666666667 0.0 521.715
0 -271 -179 0 0.0 3.0506545 0.06891391666666667 0.0 521.720000375
```

2. The delta-T values can be confusing to interpret.
```
0 -271 -171 0 0.0 3.0506545 53.339837625 0.0 523.840001958
0 -271 -170 0 0.0 3.0506545 53.339837625 0.0 523.855001
0 -271 -170 0 0.0 3.0506545 53.339837625 0.0 523.860002208
0 -271 -169 0 0.0 3.0506545 53.339837625 0.0 523.875000458
0 -271 -169 0 0.0 3.0506545 53.339837625 0.0 523.880001666
0 -271 -168 0 0.0 3.0506545 1.0299253333333334 0.0 523.895000708
0 -271 -168 0 0.0 3.0506545 1.0299253333333334 0.0 523.900001125
0 -271 -168 0 0.0 3.0506545 1.0299253333333334 0.0 523.920001583
0 -271 -167 0 0.0 3.0506545 1.0299253333333334 0.0 523.925000041
0 -271 -166 0 0.0 3.0506545 1.0299253333333334 0.0 523.940001
0 -271 -166 0 0.0 3.0506545 1.0299253333333334 0.0 523.945000041
0 -271 -165 0 0.0 3.0506545 1.0299253333333334 0.0 523.96000175
0 -271 -164 0 0.0 3.0506545 1.0299253333333334 0.0 523.965002041
0 -271 -164 0 0.0 3.0506545 1.0299253333333334 0.0 523.980002
0 -271 -164 0 0.0 3.0506545 1.0299253333333334 0.0 523.985000541
0 -271 -163 0 0.0 3.0506545 1.0299253333333334 0.0 523.995002291
0 -271 -163 0 0.0 3.0506545 1.0299253333333334 0.0 524.000000083
0 -271 -161 0 0.0 3.0506545 1.0299253333333334 0.0 524.025002125
0 -271 -161 0 0.0 3.0506545 1.0299253333333334 0.0 524.03
0 -271 -160 0 0.0 3.0506545 0.14015270833333335 0.0 524.045002
0 -271 -160 0 0.0 3.0506545 0.14015270833333335 0.0 524.050002125
0 -271 -160 0 0.0 3.0506545 0.14015270833333335 0.0 524.060001208
0 -271 -160 0 0.0 3.0506545 0.14015270833333335 0.0 524.065001416
0 -271 -160 0 0.0 3.0506545 0.14015270833333335 0.0 524.080001125
0 -271 -159 0 0.0 3.0506545 0.14015270833333335 0.0 524.085001166
0 -271 -159 0 0.0 3.0506545 0.14015270833333335 0.0 524.100001083
0 -271 -159 0 0.0 3.0506545 0.14015270833333335 0.0 524.105000041
0 -271 -158 0 0.0 3.0506545 0.14015270833333335 0.0 524.120000583
0 -271 -158 0 0.0 3.0506545 0.14015270833333335 0.0 524.125001625
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.140000333
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.145001625
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.160001625
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.165002291
0 -271 -158 0 0.0 3.0506545 0.14015270833333335 0.0 524.180000541
0 -271 -158 0 0.0 3.0506545 0.14015270833333335 0.0 524.185001958
0 -271 -158 0 0.0 3.0506545 0.14015270833333335 0.0 524.200002125
0 -271 -158 0 0.0 3.0506545 0.14015270833333335 0.0 524.205001833
0 -271 -158 0 0.0 3.0506545 0.14015270833333335 0.0 524.220002166
0 -271 -158 0 0.0 3.0506545 0.14015270833333335 0.0 524.225002041
0 -271 -158 0 0.0 3.0506545 0.14015270833333335 0.0 524.240001958
0 -271 -158 0 0.0 3.0506545 0.14015270833333335 0.0 524.245001
0 -271 -158 0 0.0 3.0506545 0.14015270833333335 0.0 524.25500025
0 -271 -158 0 0.0 3.0506545 0.14015270833333335 0.0 524.26000025
0 -271 -158 0 0.0 3.0506545 0.14015270833333335 0.0 524.275002125
0 -271 -158 0 0.0 3.0506545 0.14015270833333335 0.0 524.280000458
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.295001791
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.300000791
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.310001291
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.315001458
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.330000208
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.33500075
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.350002125
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.355000375
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.3700005
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.375000583
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.390000791
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.395001375
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.410001166
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.415002291
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.43
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.4350005
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.4500015
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.455001375
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.470001375
0 -271 -157 0 0.0 3.0506545 0.14015270833333335 0.0 524.475002125
0 -271 -156 0 0.0 3.0506545 0.14015270833333335 0.0 524.485001333
0 -271 -156 0 0.0 3.0506545 0.14015270833333335 0.0 524.49000075
0 -271 -156 0 0.0 3.0506545 0.14015270833333335 0.0 524.5050015
0 -271 -156 0 0.0 3.0506545 0.14015270833333335 0.0 524.51000075
0 -271 -155 0 0.0 3.0506545 0.14015270833333335 0.0 524.525000291
0 -271 -155 0 0.0 3.0506545 0.14015270833333335 0.0 524.53000175
0 -271 -153 0 0.0 3.0506545 0.14015270833333335 0.0 524.545001791
0 -271 -152 0 0.0 3.0506545 0.5181635833333333 0.0 524.550000208
0 -271 -152 0 0.0 3.0506545 0.5181635833333333 0.0 524.560001541
0 -271 -152 0 0.0 3.0506545 0.5181635833333333 0.0 524.565001583
0 -271 -150 0 0.0 3.0506545 0.5181635833333333 0.0 524.580001875
```
The initial MotorC delta-T of `53.339837625` include pause time in the motor rotation (not shown). Consequently we would need to skip the initial delta-T value until a new reading is acquired before it can be considered as being a correct measurement. However, once the motor stops, the delta-T again becomes invalid, so we also need to look for patterns in the Motor C position for constant values (at around the `-157` count) to determine when we should discard the last delta-T reading.

What are the correct thresholds, etc. however, I have no idea.

**Comment by laurensvalk** [comment]
Just for context:
[This comment](https://github.com/ev3dev/ev3dev/issues/853#issuecomment-398699929) ultimately amounts to equation (2) on page 10.

And [this pseudocode](https://github.com/ev3dev/ev3dev/issues/853#issuecomment-399521515) amounts to equation (1) on page 10. However, instead of doing ``x(k)-x(k-1)``, we can choose the window size.

**Comment by laurensvalk** [comment]
To work out parameters for such algorithms, it's helpful to define desired specifications first. One of them is:

1. _What is the lowest speed (deg/s) we'd like to detect as nonzero?_

For context, 1 deg/s for a motor with a 20 mm radius wheel means driving at 0.35 mm per second. (Extremely slow.) So, we may not need to go that low.

This is a separate issue from the resolution:

2. _What is the desired resolution at this minimum speed?_
3. _What is the desired resolution at 1000 deg/s?_

**Comment by dlech** [comment]
> The delta-T values can be confusing to interpret.

The data does not contain a ΔT value, only a timestamp. You have to compute ΔT by subtracting the previous timestamp from the current timestamp. The timestamp value in python is in seconds, not nanoseconds.

**Comment by dlech** [comment]
![5](https://user-images.githubusercontent.com/963645/42127246-42f8cf98-7c5a-11e8-8e0d-23d4e7c1b32f.png)
![10](https://user-images.githubusercontent.com/963645/42127247-432c7cc6-7c5a-11e8-845f-c298c8c762f8.png)
![25](https://user-images.githubusercontent.com/963645/42127248-43621610-7c5a-11e8-9321-e48cdaabf482.png)
![50](https://user-images.githubusercontent.com/963645/42127249-439f5994-7c5a-11e8-90b9-1f343dde20c9.png)
![75](https://user-images.githubusercontent.com/963645/42127250-43e5ebb6-7c5a-11e8-9865-ab7f61e4d6d1.png)
![100](https://user-images.githubusercontent.com/963645/42127251-43ff641a-7c5a-11e8-88a1-e54b02e6d9c3.png)







Source: [ev3-large-motor-analysis.xlsx](https://github.com/ev3dev/ev3dev/files/2152013/ev3-large-motor-analysis.xlsx)

**Comment by dlech** [comment]
In the charts above, the "T =" data values are the speed calculated using equation (1) and the "X =" value is calculated using equation (2). As expected, equation (2) is more accurate at low speeds and equation (1) is more accurate at high speeds. The accuracy of T = 100 and X = 8 being about the same at 25% duty cycle as well as T = 50 and X = 8 being about the same at 50& duty cycle.

**Comment by dlech** [comment]
Given the extreamly low resolution of these motors, perhaps we should approach these questions not as "what do we want", but "what is actually possible"

> To work out parameters for such algorithms, it's helpful to define desired specifications first. One of them is:
> 
>     What is the lowest speed (deg/s) we'd like to detect as nonzero?

Give the current 1% resolution of duty cycle (we can only change duty cycle in whole number increments of 1%), the slowest I could get the large motor to run was at 5% duty cycle (and I had to give it a manual kick start because there was not enough torque to move it if it was not already moving) was around 25-30 counts per second, which is about 13-15 degrees per second.

At 25 counts per second, we only get a count every 40ms, so we have to wait at least this long before deciding that the speed is 0.

> 
> For context, 1 deg/s for a motor with a 20 mm radius wheel means driving at 0.35 mm per second. (Extremely slow.) So, we may not need to go that low.

Laurens' robot would be traveling at 5mm/s at this rotational speed.

> 
> This is a separate issue from the resolution:
> 
>     What is the desired resolution at this minimum speed?

Using equation (2) with X=8 as shown in my charts, the resolution at speeds <= 350 counts per second is greater than the inherent fluctuations in the motor. So, it looks like we have sufficient resolution here. (Presumably the fluctuations come from imperfections in the internal gearing of the motor.)

>     What is the desired resolution at 1000 deg/s?

I think the better question here is how old can we stand the speed value to be? As you can see in the charts above, using T = 5ms, a difference of 1 count make a difference of 200 counts/s (100 deg/s). T = 50ms gets us +/- 20 counts/s (+/-10 deg/s), which is 1% at 1000 deg/s, but the error will be higher at slower speeds. T = 100ms gets us +/- 10 counts/s (+/-5 deg/s), which is 1% at 500 deg/s. But at this point, our "instantaneous speed" really means the average speed 50ms ago.

However, if you consider the impulse response of the motor (0 to 100% duty cycle instantaneously), it takes the motor somewhere in the neighborhood of 100 to 200ms to accelerate from 0 to max speed.

**Comment by dlech** [comment]
Also, along the lines of what possible, it turns out that the 4 transitions of the quadrature encoder are not equidistant, so X must be a multiple of 4, otherwise we introduce noise. It also explains why there are sometimes 3 bands on the T= graphs instead of 2.

**Comment by dlech** [comment]
![large-motor](https://user-images.githubusercontent.com/963645/42138292-a330fa02-7d40-11e8-94d2-6dea4f9a506e.png)
![medium-motor](https://user-images.githubusercontent.com/963645/42138296-a5063b08-7d40-11e8-8380-9016b40de74f.png)
Source: [motor-profile.xlsx](https://github.com/ev3dev/ev3dev/files/2153157/motor-profile.xlsx)

**Comment by dlech** [comment]
Here is my current iteration of the tacho driver compared to the current ev3dev driver.

Basically, I have implemented @laurensvalk's suggestion https://github.com/ev3dev/ev3dev/issues/853#issuecomment-398699929

The conclusions I draw from this are:
1. The old driver is not bad at medium and high speeds.
2. The old driver is bad at low speeds (which we already knew).
3. The new driver also struggles at low speeds but is significantly improved. I'm not sure if this can be improved any more or not. I suspect that it has to do with the unevenly spaced encoder counts when looking at < 4 counts.
4. The EV3 Large motor seems to get noisy as the speed increases. Since the EV3 Medium motor does not also exhibit this, it tells me it is a hardware issue, rather than software.

What do you guys think? Is this good enough? Anything else we could do for the low speeds?

**Comment by dlech** [comment]
> The new driver also struggles at low speeds but is significantly improved. I'm not sure if this can be improved any more or not. I suspect that it has to do with the unevenly spaced encoder counts when looking at < 4 counts.

Now that I am thinking about it again, this might be a consequence of my zero speed detection.

**Comment by dlech** [comment]
![large-motor](https://user-images.githubusercontent.com/963645/42138619-de5c7214-7d45-11e8-99c5-bff3a0f91c76.png)
![medium-motor](https://user-images.githubusercontent.com/963645/42138620-e01dd4c6-7d45-11e8-8ccd-739a5351eca9.png)



Source: [motor-profile.xlsx](https://github.com/ev3dev/ev3dev/files/2153173/motor-profile.xlsx)

**Comment by dlech** [comment]
How do you like it now?

**Comment by tcwan** [comment]
@dlech:
Looks good!

Some comments:

1. Now that you've reverted to using a shared memory buffer for data transfer, would it be safer to have a semaphore to indicate to the driver when the buffer is being updated? When the `pru_rpmsg_send()` returns the address pointer, is it copied to another buffer by the kernel driver?

I had a semaphore updated by the PRU0 code in my branch, if you'd like a reference.

2. would it be safer to initialize out the memory buffer at the beginning? 

3. @laurensvalk's [pseudocode](https://github.com/ev3dev/ev3dev/issues/853#issuecomment-399521515) duplicated the latest reading to the entire buffer to make it easier to calculate the speed on (re)start. Should this be part of the PRU0 code?

**Comment by dlech** [comment]
> would it be safer to have a semaphore to indicate to the driver when the buffer is being updated?

the kernel driver is reading from the same "head" as the PRU and is only looking back up to 64 values. I made the buffers big enough that we shouldn't have to worry about it. It would take 500ms for the PRU to write over where the kernel is reading when a motor is running at max speed and longer if the motor is running slower or stopped.

> When the pru_rpmsg_send() returns the address pointer, is it copied to another buffer by the kernel driver?

No, the physical address is just remapped to a virtual address.

> would it be safer to initialize out the memory buffer at the beginning?

It is zeroed out in the kernel driver probe function

> @laurensvalk's pseudocode duplicated the latest reading to the entire buffer to make it easier to calculate the speed on (re)start. Should this be part of the PRU0 code?

A new value is added to the ring buffer ever 50ms if the motor is not moving. When this is the case, the kernel driver only looks back 4 counts. I suppose there could be a problem if you started reading data < 200ms after the driver loaded, but I don't see how that could happen, practically speaking.

**Comment by dlech** [comment]
So I've just done a kernel release (`ev3dev-2.1.0`) that includes the new PRU tachometer. To use it, grab the latest ev3dev-stretch image or make sure all of your packages are up to date (you may have to manually run `sudo flash-kernel` after upgrading the kernel if it doesn't do it automatically).

After (re)boot, run `sudo sh -c 'echo start > /sys/class/remoteproc/remotreproc0/state'`. You should now have some interesting stuff at `/sys/bus/iio/devices/iio:device1/`. You can use these attributes just as you would the `tacho-motor` class attributes. Note: the counts are 720/rotation instead of 360. The speed should be more accurate (the `tacho-motor` speed will still be the old, less accurate value).

I'm interested to see what can be done from userspace using these values.

**Comment by WasabiFan** [comment]
@dlech is that `echo` command missing a `>`?

**Comment by dlech** [comment]
oops. It's fixed now.

**Comment by dlech** [comment]
I've just release kernel `ev3dev-2.2.0` which automatically loads the firmware and patches the new readings into the old motor driver (so the "tacho-motor speed attribute is inaccurate at low speeds" issue is fixed).

What is next?

**Comment by laurensvalk** [comment]
Great work everyone. 

> What is next?

I'll have to plug it in [here](https://github.com/laurensvalk/segway/blob/eab678399ada5b563c497a0a4e190f082b796184/ev3/ev3dev/pythonic/segway.py#L84) to see how well it works :smile:

**Comment by tcwan** [comment]
Would this new patch make TACHO_RUN_TO_REL_POS work better?
I find that it tends to overshoot.

**Comment by dlech** [comment]
I don't think so. Do you enable ramping? Otherwise, I don't think the motor driver will even think about stopping until it is past the position setpoint.

**Comment by tcwan** [comment]
Yes, I enabled ramping 100 ms for both up and down.
I'm not familiar enough with the knobs to know what I should default them to.

**Comment by dlech** [comment]
100ms is probably too short to notice anything. Try setting them for a long time to get a feel for how they work (e.g. 5000ms), then make it shorter. I don't know that these settings ever get used, so it is possible they are broken, but at one point, they did work. You can search existing issues to read more about how ramping is supposed to work if the documentation is not clear.

**Comment by dlech** [comment]
Anyway, ramping has nothing to do with the topic of this issue (motor synchronization), so let's open a new issue if there are further problems on that subject.

**Comment by jabrena** [comment]
Hi mates,

What is the status of this feature?
Does exist some way to use with the latest snapshot?

Merry christmas and happy new year

Cheers

Juan Antonio

**Comment by dlech** [comment]
As far as I know, no one is working on motor synchronization.

**Comment by staadecker** [comment]
What would be the next steps to implement motor synchronization?

**Comment by dwalton76** [comment]
You can get very close using the MotorSet class in the python library

**Comment by staadecker** [comment]
@dwalton76 Ok. That's what I've been using. However, is ramping supported? I couldn't find any functions to do so.

**Comment by dwalton76** [comment]
Yep you should be able to do something like
```
from ev3dev2.motor import MotorSet

ms = MotorSet(....)
ms.set_args(ramp_up_sp=100)
```

I think in practice most folks end up using `MoveTank` more often than `MotorSet` (`MoveTank` is a child class of `MotorSet`).  MoveTank will set all of the parameters it can for both motors and then at the end will tell one motor to start moving and then right after that tell the other motor to start moving.  While it isn't starting both motors at the exact same time, the gap is very very narrow.

**Comment by staadecker** [comment]
Ok thank you!
